### PR TITLE
Test other PPA

### PR DESCRIPTION
**Pull request by jeroen**
Test if this fixes the very strange imagemagick error on travis.

### CODE REVIEW

**Comment by jwijffels** [comment]
Thanks. 
Is remember having seen this plotting error with magick also several times with the other image.* packages which I've put on CRAN. Thanks for fixing.

```
> plt <- image_draw(img)

Error in graphics::mtext(sprintf("help(\"%s\")", nameEx()), side = 4,  : 

  R: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1367

malloc(): smallbin double linked list corrupted

Aborted (core dumped)
```

**Comment by jeroen** [comment]
Very strange, I have never seen that before. Does it only happen on travis or also locally?

**Comment by jwijffels** [comment]
Only had it on travis, I'm mainly developing on Windows so don't know exactly what was the cause on other platforms. I thought it was some font which was not available on these systems but I didn't dig deeper.

**Comment by jwijffels** [comment]
fyi here I had another one https://travis-ci.org/github/bnosac/image/jobs/509520490 for package image.CornerDetectionHarris which is now on cran

**Comment by jeroen** [comment]
I'm not seeing the errors on CRAN, perhaps Travis has some weird font configuration on their images. Have you ever seen this in a docker container?

**Comment by jwijffels** [comment]
Never tested this in a docker container so don't know.

**Pull request closed without merging**
