### PR TITLE
Windows: update to opencv 4.8.1 with support for arm64.

### PR DESCRIPTION
**Pull request by jeroen**
Copy setup from opencv package.

### CODE REVIEW

**Comment by jeroen** [comment]
Also fixed the CI on MacOS .

**Comment by jwijffels** [comment]
Looks great. Thanks for the upgrade of opencv and the upstream fixes!

**Comment by jwijffels** [comment]
> Also fixed the CI on MacOS .

Yes, I saw it, thanks. I must have copied it somehow without that `test ! "$CI"` setting

**Comment by jeroen** [comment]
Can you submit this to CRAN when you have a chance? They are working on getting things to work on ARM64.

**Comment by jwijffels** [comment]
I tried 2 days ago but it did not pass the preliminary checks due to timing issues of the examples on the debian machine. I think these are caused by magick operations in the examples which use the file system. I tried to explain it and I´m now awaiting their response.

**Comment by jeroen** [comment]
Yes I had similar problems. They have som every weird rules that disallow multithreading, but this is very difficult to prevent in external libraries like imagemagick. I ended up doing something like this: https://github.com/ropensci/magick/commit/fd53da8f040ed91d87a91c4f363120729f2e2441

**Comment by jwijffels** [comment]
Yes, I explained cran that I´d be obliged to put the examples in a donttest block. But haven´t heard back from them yet. 
If I don´t get an answer, I´ll wrap it up in donttest blocks next week and reupload.

**Comment by jwijffels** [comment]
I haven't heard back from CRAN. I've put the examples in a donttest block.
When looking at the R CMD check logs of the continuous integration on Mac I noticed: https://github.com/DIGI-VUB/image.textlinedetector/actions/runs/6768346596/job/18392600689#step:5:97
Is that something cran will allow?

```
objc[7171]: Class CVWindow is implemented in both /Users/runner/work/image.textlinedetector/image.textlinedetector/check/image.textlinedetector.Rcheck/image.textlinedetector/libs/image.textlinedetector.so (0x109cb9b80) and /Users/runner/work/_temp/Library/opencv/libs/opencv.so (0x10bbd3240). One of the two will be used. Which one is undefined.
objc[7171]: Class CVView is implemented in both /Users/runner/work/image.textlinedetector/image.textlinedetector/check/image.textlinedetector.Rcheck/image.textlinedetector/libs/image.textlinedetector.so (0x109cb9ba8) and /Users/runner/work/_temp/Library/opencv/libs/opencv.so (0x10bbd3268). One of the two will be used. Which one is undefined.
objc[7171]: Class CVSlider is implemented in both /Users/runner/work/image.textlinedetector/image.textlinedetector/check/image.textlinedetector.Rcheck/image.textlinedetector/libs/image.textlinedetector.so (0x109cb9bd0) and /Users/runner/work/_temp/Library/opencv/libs/opencv.so (0x10bbd3290). One of the two will be used. Which one is undefined.
```

**Comment by jwijffels** [comment]
FYI. I pushed it to CRAN yesterday wrapping the examples in donttest to avoid timing issues.

**Pull request merged**
